apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong-app
  namespace: app1
spec:
  selector:
    matchLabels:
      app: pong-app
  template:
    metadata:
      labels:
        app: pong-app
    spec:
      serviceAccountName: "app1-sa"
      containers:
        - name: pong-app
          image: docker.io/s3b4s/pong-app:co-signed
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
