apiVersion: v1
kind: Service
metadata:
  name: pong-app
  labels:
    app: pong-app
spec:
  type: NodePort
  ports:
    - port: 8181
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: pong-app